#!/bin/bash
echo "ALX"
#!/bin/bash
echo "ALX"
#!/bin/bash
echo "ALX SCHOOL"
#!/bin/bash
echo "ALX School"
#!/bin/bash
echo "ALX School is so cool!"
#!/bin/bash
echo "ALX School is so cool!"
#!/bin/bash
echo "ALX School is so cool!"
